AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for HelloWorld

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  GloomAppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/Gloom
      Handler: Gloom::Gloom.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        NewSession:
          Type: Api
          Properties:
            Path: /newsession
            Method: post
        GetScenario:
          Type: Api
          Properties:
            Path: /getscenario
            Method: post
        SetElement:
          Type: Api
          Properties:
            Path: /setelement
            Method: post
        SetScenario:
          Type: Api 
          Properties:
            Path: /setscenario
            Method: post
        AddMonster:
          Type: Api 
          Properties:
            Path: /addmonster
            Method: post
        RemoveMonster:
          Type: Api 
          Properties:
            Path: /removemonster
            Method: post
        UpdateMonsterState:
          Type: Api
          Properties:
            Path: /updatemonsterstate
            Method: post
        DrawAbility:
          Type: Api 
          Properties:
            Path: /drawability
            Method: post
        DrawForGroup:
          Type: Api 
          Properties:
            Path: /drawforgroup
            Method: post
        AddCharacter:
          Type: Api
          Properties:
            Path: /addcharacter
            Method: post
        SetInitiative:
          Type: Api
          Properties:
            Path: /setinitiative
            Method: post
        EndRound:
          Type: Api 
          Properties:
            Path: /endround
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GloomAppApi:
    Description: "API Gateway endpoint URL for Prod stage for Gloom App function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/gloomapp/"
  GloomAppFunction:
    Description: "Gloom App Lambda Function ARN"
    Value: !GetAtt GloomAppFunction.Arn
  GloomAppFunctionIamRole:
    Description: "Implicit IAM Role created for Gloom App function"
    Value: !GetAtt GloomAppFunctionRole.Arn
